### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by happyCodingSusan** [bardiadoosti/HOPE#11]
@bardiadoosti , great work! Thanks for sharing your codes!

I'd like to ask  some questions. Can we use your pretrained model (which is trained on the fhad dataset) on HO-3D Dataset, or on my own dataset (assuming the objects and hands in my dataset are of similar size to those in fhad dataset) and output good 3D poses of hands and objects? In other words, are you able to train on fhad and HO-3D datasets to generate a model that will work for both datasets?

Thanks very much for your kind reply!

**Comment by bardiadoosti** [comment]
Hi, I don't think it works on both datasets, because one of them is first-person view and the other is third-person view and the size of hands and object and its position in the image differs a lot. If the hand and object's size are almost the same in both datasets it may be possible. The other possible solution is to have an object localizer to find hand and object in the image and then pass to our model.
By the way the 2D to 3D concept needs to be trained on one camera setting and if we change the cameras differ during the training this network may not be trained very well.

**Comment by happyCodingSusan** [comment]
@bardiadoosti , thanks very much for your fast reply!
>>The 2D to 3D concept needs to be trained on one camera setting
This is a huge problem. In order to use on another camera, we have to re-collect a huge amount of 3D data, label 3D poses, and re-train. It seems not very practical. Do you have other suggestions?

Thanks!!

**Comment by bardiadoosti** [comment]
This is not this method's problem. Every 3D pose estimation from a single image has this problem. 2D estimation does not depend on camera settings but 3D definitely does.
