### ISSUE TITLE
About Net struct

### ISSUE THREAD

**Issue by www516717402** [bardiadoosti/HOPE#5]
Thank you for great project.
The Net use Linear struct, output 2d shape: num_keypoints * 2, 3d shape: num_keypoins * 3 respectly. However regression coordinate directly always in previous, almost use heatmap in recently.Have you ever test heatmap in your project?

**Comment by bardiadoosti** [comment]
It is mentioned in the section 4.2 and depicted in Fig 4 of the paper that since in the FPHA dataset (which we had to test on to compare to previous papers) there are so many points which are outside the frame, we didn't find the detection based methods (heatmaps) useful and used regression based method.
You can use your favorite detection based network to find the 2D coordinates and then use our Adaptive Graph U-Net to get the 3D coordinates.
